spring.application.name=pc-configurer
security.jwt.expiration-time=600000
security.jwt.refresh.expiration-time=72000000
spring.datasource.url=${CONFIGURER_POSTGRES_PATH}
spring.datasource.username=${CONFIGURER_POSTGRES_NAME}
spring.datasource.password=${CONFIGURER_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=${JWT_SECRET}
logging.file.name=configurer.log
logging.file.path=logs
